name1 = input("Enter name #1: ")
gpa1 = float(input("Enter GPA #1: "))
name2 = input("Enter name #2: ")
gpa2 = float(input("Enter GPA #2: "))

print(f"+-----------+-------+")
print(f"|   Name    |  GPA  |")
print(f"+-----------+-------+")
print(f"| {name1:9} | {gpa1:.2f}  |")
print(f"| {name2:9} | {gpa2:.2f}  |")
print(f"+-----------+-------+")
